### ISSUE TITLE
Cloud Deployment

### ISSUE THREAD

**Issue by Sagar2366** [naXa777/spring-cloud-example#9] opened 2018-10-07 13:18 UTC
- Add Continuous Integration section in README.

**Comment by naXa777** [comment] 2018-10-07 14:46
It seems like a duplicate of #8 . Why is it different?

**Comment by Sagar2366** [comment] 2018-10-07 14:56
Because it was not specified in #8 [](https://github.com/naXa777/spring-cloud-example/issues/8)

**Closed** 2023-10-17 11:13 UTC
